### ISSUE TITLE
Implement `run` build step

### ISSUE THREAD

**Issue by omacha** [lando/laravel#78]
I saw in the code that the build steps `build`, `build_as_root` and `run_as_root` are implemented for this plugin but it seems the `run` build step Is missing. Was this intentional?

https://github.com/lando/laravel/blob/0a2c8955087da4870afe051d95c10529c4b58a69/builders/laravel.js#L158-L163

I would love to use this step to make a `php artisan migrate` script that automatically runs on first boot. The build step does not have the database container initialized so I can't execute it there.

**Comment by AaronFeledy** [comment]
I think that code just ties in some internal build processes. The `run` steps are handled by Lando, so they should still work when you add them to your landofile.
