### ISSUE TITLE
Change lavarel/installer version for PHP <=7.3

### ISSUE THREAD

**Issue by andrewanswer** [lando/laravel#9]
Your notice "Allows users to configure php version from 5.3 all the way to 8.1" is wrong because. if you change PHP to the version before 7.3 you'll see Composer warning; it's because laravel/installer have a restriction php: ^7.3|^8.0. You need to change laravel/installer version to 4.0.0 or less to allow PHP 7.2 used correctly. Please fix it.

**Comment by labboy0276** [comment]
@andrewanswer thank you for reporting it.  I went ahead and adjusted the `laravel/installer` version to the corresponding php version via https://github.com/lando/laravel/pull/11.

I tagged a 0.5.2 release and this will be part of the Lando 3.6.3 release when that happens.
